# Generated by Django 5.2.3 on 2025-06-17 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='booking_requests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100)),
                ('client_email', models.EmailField(max_length=254)),
                ('fitness_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.fitness_studio')),
            ],
        ),
    ]
